Import styles
Jay-Gadhiya/SilkShopy-ecommerce pull request #1
Opened 2022-03-15 14:25 UTC by Jay-Gadhiya

Home Page: https://www.awesomescreenshot.com/image/24098122?key=b4110f514163efa933f4e4c0bc8ef494
 Products : https://www.awesomescreenshot.com/image/24098120?key=daebbbbf703ab2b111f798f72c2da8fe
 Cart : https://www.awesomescreenshot.com/image/24098118?key=7a1eab3083ec3e18452e95ab87252a0a
 wish list : https://www.awesomescreenshot.com/image/24098116?key=997e0a4538197b73e6bcc3b659950edb
 login : https://www.awesomescreenshot.com/image/24098115?key=24c98da1d83dd05ff0db94a422b47fb9
 sign up : https://www.awesomescreenshot.com/image/24098114?key=c7c724173ddd292c40664e235f1adfe0
 
 changes in folders: pages and components

2022-03-15 14:47 UTC, RahullRawat requested changes
1. You have used class at multiple places, my suggestion is that you can replace class with **className**
2. Also replace for attribute with **htmlFor**

2022-03-16 03:50 UTC, Jay-Gadhiya commented
> 1. You have used class at multiple places, my suggestion is that you can replace class with **className**
> 2. Also replace for attribute with **htmlFor**

2022-03-16 04:00 UTC, AtulPant2704 approved these changes

2022-03-16 04:06 UTC, AtulPant2704 reviewed
- Really liked that you used similar stylesheet for login as well as signup page.
- You extracted out cart bill as a separate component not just kept it in Cart component itself, that was a good thing to do.
- Just a small sugesstion that you can have one file as index.js from where you can export all the components.

2022-03-16 05:13 UTC, merged